### PR TITLE
Refactor xres namespace to be x11 agnostic

### PR DESCRIPTION
**Pull request by kgilmer**
Rename i3-wm to wm in Xres keys for compat w/ wayland

Related to https://github.com/regolith-linux/regolith-look-default/pull/5

### CODE REVIEW

**Comment by SoumyaRanjanPatnaik** [comment]
I guess we'd also need to change the file names to be wm agnostic (currently they're name `i3-wm`).

**Review by SoumyaRanjanPatnaik — CHANGES_REQUESTED** [review]
I guess we'd also need to change the file names to be wm agnostic (currently they're name i3-wm).

**Comment by kgilmer** [comment]
nice catch, fixed

**Review by SoumyaRanjanPatnaik — APPROVED** [review]
LGTM

**Pull request merged**
